"""New Migration

Revision ID: 92f4f0a6fe4f
Revises: 1190c1526378
Create Date: 2023-12-19 21:40:24.555602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92f4f0a6fe4f'
down_revision: Union[str, None] = '1190c1526378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('bill_code', sa.String(), nullable=True))
    op.add_column('content', sa.Column('bill_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content', 'bill_date')
    op.drop_column('content', 'bill_code')
    # ### end Alembic commands ###
