"""New Migration

Revision ID: c5e7618c046d
Revises: 
Create Date: 2023-12-16 15:35:12.205264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5e7618c046d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice',
    sa.Column('code_invoice', sa.String(), nullable=False),
    sa.Column('number_of_invoice', sa.String(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('organization_code', sa.String(), nullable=True),
    sa.Column('document_number', sa.String(), nullable=True),
    sa.Column('document_date', sa.String(), nullable=True),
    sa.Column('organization_received', sa.String(), nullable=True),
    sa.Column('bank_account', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('code_invoice')
    )
    op.create_index(op.f('ix_invoice_code_invoice'), 'invoice', ['code_invoice'], unique=False)
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invoice_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.code_invoice'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_content'), 'content', ['content'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_content'), table_name='content')
    op.drop_table('content')
    op.drop_index(op.f('ix_invoice_code_invoice'), table_name='invoice')
    op.drop_table('invoice')
    # ### end Alembic commands ###
